### ISSUE TITLE
fullnode conntection node

### ISSUE THREAD

**Issue by lijianl** [aptos-labs/aptos-networks#7]
error for testnet connection, could you give some advice for local fullnode connection to testnet

1. run command

```bash
docker run -d \
    -p 18080:8080 \
    -p 9101:9101 -p 6180:6180 \
    -v $(pwd):/opt/aptos/etc -v $(pwd)/data:/opt/aptos/data \
    --workdir /opt/aptos/etc \
    --name=aptos-fullnode aptoslabs/validator:testnet_8f0cbd9396264cdce520d2e1002424b1592c576f aptos-node \
    -f ./fullnode.yaml
```

2. download file

```
curl -O https://github.com/aptos-labs/aptos-networks/blob/main/testnet/waypoint.txt
curl -O https://github.com/aptos-labs/aptos-networks/blob/main/testnet/waypoint.txt
```

3. fullnode.yml 

```yaml
base:
  role: "full_node"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_file: "/opt/aptos/etc/waypoint.txt"

execution:
  genesis_file_location: "/opt/aptos/etc/genesis.blob"

full_node_networks:
- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/127.0.0.1/tcp/6182"
  max_inbound_connections: 100

mempool:
  shared_mempool_max_concurrent_inbound_syncs: 16 # default 4
  max_broadcasts_per_peer: 4 # default 1
  default_failovers: 0 # default 3
  shared_mempool_batch_size: 200 # default 100
  shared_mempool_tick_interval_ms: 10 # default 50

api:
  enabled: true
  address: "0.0.0.0:8080"
```

the  error met is

```bash
thread 'main' panicked at 'Failed to parse node config file! Given file path: "./fullnode.yaml". Error: Unexpected("Failed to BCS deserialize the genesis file: \"/opt/aptos/etc/genesis.blob\". Error: Custom(\"invalid value: integer `10`, expected variant index 0 <= i < 4\")")', aptos-node/src/lib.rs:151:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: aptos_node::AptosNodeArgs::run::{{closure}}
             at /aptos/aptos-node/src/lib.rs:151:17
   3: core::result::Result<T,E>::unwrap_or_else
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1484:23
   4: aptos_node::AptosNodeArgs::run
             at /aptos/aptos-node/src/lib.rs:150:26
   5: aptos_node::main
             at /aptos/aptos-node/src/main.rs:14:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lijianl** [comment]
could you give some advice for this, what should i do to connect a testnet


```yaml
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  seeds:
    00000000000000000000000000000000d58bc7bb154b38039bc9096ce04e1237:
      addresses:
      - "/ip4/<Validator IP Address>/tcp/6181/noise-ik/f0274c2774519281a8332d0bb9d8101bd58bc7bb154b38039bc9096ce04e1237/handshake/0"
      role: "Validator"
```
